default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(
      scheme: "App",
      devices: ["iPhone 15"]
    )
  end

  desc "Ship a build to TestFlight"
  lane :beta do
    build_app
    upload_to_testflight
  end
end
